project:
  type: website
  resources:
    - fonts/

website:
  title: "Magical algorithms"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - articles.qmd
      - about.qmd
  sidebar:
    style: docked
    contents:
      - articles.qmd
      - section: "Decision Trees"
        href: articles/decision-trees/index.qmd
        contents: "articles/decision-trees/*/index.qmd"
      - text: "Causal Inference"
        href: articles/causal-inference/index.qmd
      - text: "Generative AI"
        href: articles/gen-ai-and-agentic-workflow/index.qmd

format:
  html:
    theme:
      light: [cosmo, brand, light.scss]
      dark: cyborg
    grid:
      margin-width: 600px
    respect-user-color-scheme: true
    css: styles.css
    lang: en
    toc: true
    mainfont: "New Computer Modern"

execute:
  freeze: auto